kind: pipeline
type: kubernetes
name: dnscontrol

steps:
  - name: preview
    image: stackexchange/dnscontrol:latest
    settings:
      from_secret: docker_secret
    commands:
      - printenv DNSCONTROL_CREDS | tee creds.json
      - cat creds.json
      - dnscontrol preview