kind: pipeline
type: kubernetes
name: dnscontrol

steps:
  - name: preview
    image: stackexchange/dnscontrol:latest
    settings:
      from_secret: docker_secret
    environment:
      CLOUD_FLARE_API_TOKEN:
        from_secret: CLOUD_FLARE_API_TOKEN
    commands:
      - dnscontrol preview
    when:
      - push
      - pull_request

  - name: deploy
    image: stackexchange/dnscontrol:latest
    settings:
      from_secret: docker_secret
    environment:
      from_secret: CLOUD_FLARE_API_TOKEN
    commands:
      - dnscontrol push
    when:
      event:
        - promote
      target:
        - prod